job1:
  tags:
    - self-hosted
  script:
    - mkdir build
    - python3 -m pip install --user pspartition
    - python3 alg_speed.py --total_times --num_times 1 --task gaussian
    - cat build/*.log 
